"""Initial schema setup

Revision ID: 41a83d54201d
Revises: 
Create Date: 2025-05-16 18:10:48.309517

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '41a83d54201d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bugs',
    sa.Column('bug_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('reporter', sa.String(), nullable=True),
    sa.Column('severity', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('bug_id')
    )
    op.create_table('pdf_contents',
    sa.Column('pdf_id', sa.String(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=True),
    sa.Column('storage_location', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('author', sa.String(), nullable=True),
    sa.Column('creation_date', sa.DateTime(), nullable=True),
    sa.Column('modification_date', sa.DateTime(), nullable=True),
    sa.Column('num_pages', sa.Integer(), nullable=False),
    sa.Column('processing_timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('pdf_id')
    )
    op.create_table('text_contents',
    sa.Column('text_id', sa.String(), nullable=False),
    sa.Column('content', sa.String(), nullable=True),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('encoding', sa.String(), nullable=True),
    sa.Column('extraction_method', sa.String(), nullable=True),
    sa.Column('processing_timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('text_id')
    )
    op.create_table('image_contents',
    sa.Column('image_id', sa.String(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=True),
    sa.Column('storage_location', sa.String(), nullable=True),
    sa.Column('meta_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ocr_text_id', sa.String(), nullable=True),
    sa.Column('ocr_confidence', sa.Float(), nullable=True),
    sa.Column('processing_timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['ocr_text_id'], ['text_contents.text_id'], ),
    sa.PrimaryKeyConstraint('image_id')
    )
    op.create_table('pdf_pages',
    sa.Column('page_id', sa.String(), nullable=False),
    sa.Column('pdf_id', sa.String(), nullable=True),
    sa.Column('page_number', sa.Integer(), nullable=False),
    sa.Column('has_text', sa.Boolean(), nullable=True),
    sa.Column('has_images', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['pdf_id'], ['pdf_contents.pdf_id'], ),
    sa.PrimaryKeyConstraint('page_id')
    )
    op.create_table('video_contents',
    sa.Column('video_id', sa.String(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=True),
    sa.Column('storage_location', sa.String(), nullable=True),
    sa.Column('duration', sa.Float(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('format', sa.String(), nullable=False),
    sa.Column('codec', sa.String(), nullable=True),
    sa.Column('fps', sa.Float(), nullable=False),
    sa.Column('audio_text_id', sa.String(), nullable=True),
    sa.Column('processing_timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['audio_text_id'], ['text_contents.text_id'], ),
    sa.PrimaryKeyConstraint('video_id')
    )
    op.create_table('attachments',
    sa.Column('attachment_id', sa.String(), nullable=False),
    sa.Column('bug_id', sa.String(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('file_extension', sa.String(), nullable=False),
    sa.Column('file_type', sa.String(), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=True),
    sa.Column('upload_timestamp', sa.DateTime(), nullable=True),
    sa.Column('uploader', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('processing_status', sa.String(), nullable=True),
    sa.Column('processing_error', sa.String(), nullable=True),
    sa.Column('last_processed_timestamp', sa.DateTime(), nullable=True),
    sa.Column('meta_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('pdf_content_id', sa.String(), nullable=True),
    sa.Column('video_content_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['bug_id'], ['bugs.bug_id'], ),
    sa.ForeignKeyConstraint(['pdf_content_id'], ['pdf_contents.pdf_id'], ),
    sa.ForeignKeyConstraint(['video_content_id'], ['video_contents.video_id'], ),
    sa.PrimaryKeyConstraint('attachment_id')
    )
    op.create_table('pdf_page_image_association',
    sa.Column('pdf_page_id', sa.String(), nullable=True),
    sa.Column('image_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['image_id'], ['image_contents.image_id'], ),
    sa.ForeignKeyConstraint(['pdf_page_id'], ['pdf_pages.page_id'], )
    )
    op.create_table('pdf_page_text_association',
    sa.Column('pdf_page_id', sa.String(), nullable=True),
    sa.Column('text_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['pdf_page_id'], ['pdf_pages.page_id'], ),
    sa.ForeignKeyConstraint(['text_id'], ['text_contents.text_id'], )
    )
    op.create_table('video_frames',
    sa.Column('frame_id', sa.String(), nullable=False),
    sa.Column('video_id', sa.String(), nullable=True),
    sa.Column('frame_number', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.Float(), nullable=False),
    sa.Column('image_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['image_id'], ['image_contents.image_id'], ),
    sa.ForeignKeyConstraint(['video_id'], ['video_contents.video_id'], ),
    sa.PrimaryKeyConstraint('frame_id')
    )
    op.create_table('attachment_image_association',
    sa.Column('attachment_id', sa.String(), nullable=True),
    sa.Column('image_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['attachment_id'], ['attachments.attachment_id'], ),
    sa.ForeignKeyConstraint(['image_id'], ['image_contents.image_id'], )
    )
    op.create_table('attachment_text_association',
    sa.Column('attachment_id', sa.String(), nullable=True),
    sa.Column('text_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['attachment_id'], ['attachments.attachment_id'], ),
    sa.ForeignKeyConstraint(['text_id'], ['text_contents.text_id'], )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('attachment_text_association')
    op.drop_table('attachment_image_association')
    op.drop_table('video_frames')
    op.drop_table('pdf_page_text_association')
    op.drop_table('pdf_page_image_association')
    op.drop_table('attachments')
    op.drop_table('video_contents')
    op.drop_table('pdf_pages')
    op.drop_table('image_contents')
    op.drop_table('text_contents')
    op.drop_table('pdf_contents')
    op.drop_table('bugs')
    # ### end Alembic commands ###
