"""create_comments_tables

Revision ID: create_comments_tables
Revises: f879f0338a7e
Create Date: 2025-05-16 22:20:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'create_comments_tables_1'
down_revision: Union[str, None] = 'f879f0338a7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comments',
        sa.Column('comment_id', sa.String(), nullable=False),
        sa.Column('bug_id', sa.String(), nullable=False),
        sa.Column('author', sa.String(), nullable=False),
        sa.Column('text', sa.String(), nullable=False),
        sa.Column('timestamp', sa.DateTime(), nullable=True),
        sa.Column('is_private', sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(['bug_id'], ['bugs.bug_id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('comment_id')
    )

    op.create_table('comment_attachment_association',
        sa.Column('comment_id', sa.String(), nullable=True),
        sa.Column('attachment_id', sa.String(), nullable=True),
        sa.ForeignKeyConstraint(['comment_id'], ['comments.comment_id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['attachment_id'], ['attachments.attachment_id'], ondelete='CASCADE')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comment_attachment_association')
    op.drop_table('comments')
    # ### end Alembic commands ###
